[build]
  command = "npm run build"
  functions = "functions"


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
[build.environment]
  DATABASE_URL="postgresql://stien95:hi8eulKIN1co@ep-still-rice-75836050.us-east-1.aws.neon.tech/emails?sslmode=require"
